theme: just-the-docs

title: My Lecture Notes
description: A collection of lecture notes on various topics.
baseurl: "/beyond-normal-distributions-lecture-notes"

# Theme settings
just_the_docs:
  search_enabled: true
  aux_links:
    "Source Code":
      - https://github.com/miso037/beyond-normal-distributions-lecture-notes

